## Zadanie 1

Korzystając z funkcji wbudowanych w pakiet oblicz wyznaczniki z macierzy:

In [2]:
import numpy as np
a = np.array([[1, 1, 2, 1], [0, 1, 4, 3], [4, 6, 8, 6], [5, 5, -5, 5]])
print(a)

[[ 1  1  2  1]
 [ 0  1  4  3]
 [ 4  6  8  6]
 [ 5  5 -5  5]]


In [3]:
det_a = np.linalg.det(a)
print( "wyznacznik macierzy A jest równy: ", det_a)

wyznacznik macierzy A jest równy:  -59.999999999999986


In [4]:
b = np.array([[2,1,1,2], [1,2,1,2], [2,1,2,1], [2,2,2,2]])
print(b)

[[2 1 1 2]
 [1 2 1 2]
 [2 1 2 1]
 [2 2 2 2]]


In [5]:
det_b = np.linalg.det(b)
print( "wyznacznik macierzy B jest równy: ", det_b)

wyznacznik macierzy B jest równy:  3.330669073875464e-16


## Zadanie 2

Znajdź układ (kilku) równań liniowych z kilkoma niewiadomymi, który ma dokładnie jedno rozwiązanie, dla którego wbudowane metody pakietu znajdują je niedokładnie. Dla sprawdzenia poprawności rozwiązania sprawdzaj, czy $r = Ax − b$ jest zerem. Spróbuj znaleźć taki układ, dla którego r jest jak największe.

Możemy wygenerować losowy układ równań liniowych z kilkoma niewiadomymi, który będzie miał dokładnie jedno rozwiązanie, ale którego rozwiązanie będzie niedokładne dla wbudowanych metod pakietu. Do generowania takiego układu użyjemy biblioteki NumPy.
Najpierw zaimportujmy potrzebne biblioteki:

In [1]:
import numpy as np
from numpy.linalg import norm

Następnie wygenerujmy losowy układ równań liniowych z 4 niewiadomymi, który będzie miał dokładnie jedno rozwiązanie. Możemy to zrobić poprzez wylosowanie macierzy współczynników A o wymiarach 4x4 oraz wektora wyrazów wolnych b o długości 4 i obliczenie wektora rozwiązań x jako rozwiązania układu równań Ax = b:

In [2]:
A = np.random.rand(4, 4)
b = np.random.rand(4)
x = np.linalg.solve(A, b)

Teraz możemy dodać szum do wektora b, aby otrzymać niedokładne dane wejściowe dla wbudowanych metod pakietu:
python

In [3]:
b_noisy = b + 0.1 * np.random.randn(4)

Następnie możemy rozwiązać układ równań z zakłóconymi danymi wejściowymi przy użyciu wbudowanej funkcji numpy.linalg.solve() i obliczyć resztę r jako różnicę między iloczynem macierzy A i wektora x a wektorem b:

In [4]:
x_approx = np.linalg.solve(A, b_noisy)
r = np.dot(A, x_approx) - b_noisy
r

array([ 1.11022302e-16,  1.11022302e-16,  0.00000000e+00, -1.11022302e-16])

Teraz możemy sprawdzić, czy reszta r jest bliska zeru przy użyciu normy L2:

In [5]:
residual_norm = norm(r)
residual_norm

1.9229626863835638e-16

Jeśli reszta r jest bliska zeru, oznacza to, że nasze rozwiązanie jest bliskie dokładnemu rozwiązaniu układu równań Ax = b. Jednakże, dla naszego celu, chcemy znaleźć układ równań, dla którego reszta r jest jak największa. Aby to osiągnąć, możemy powtórzyć proces generowania układu równań i rozwiązywania go z różnymi losowymi wektorami wyrazów wolnych, a następnie wybrać ten układ równań, dla którego norma reszty r jest największa:

In [35]:
max_residual_norm = 0
max_residual_norm_A = None
max_residual_norm_b = None
max_residual_norm_x = None

for i in range(100):
    A = np.random.rand(4, 4)
    b = np.random.rand(4)
    x = np.linalg.solve(A, b)
    b_noisy = b + 0.1 * np.random.randn(4)
    x_approx = np.linalg.solve(A, b_noisy)
    r = np.dot(A, x_approx) - b_noisy
    residual_norm = norm(r)
    if residual_norm > max_residual_norm:
        max_residual_norm = residual_norm
        A_p = A
        b_p = b
        x_p = x
        #print(max_residual_norm)
        
max_residual_norm


1.0352061747083999e-13

In [37]:
print(A_p, b_p, x_p)

[[0.17456243 0.87335368 0.26798425 0.13711133]
 [0.20011718 0.14058807 0.1874011  0.82135816]
 [0.7789195  0.04395224 0.64578057 0.71522447]
 [0.48010389 0.14379662 0.41270693 0.15149812]] [0.25005644 0.88844171 0.98948639 0.90444754] [ 731.85201863  128.02806873 -895.69979449    5.22085636]
